"""Render a Comparison as a side-by-side Markdown or HTML table, or flat CSV."""

from __future__ import annotations

import csv
import html as _html
import io
from typing import Callable, List, Tuple

from papermind.output.schema import ComparedPaper, Comparison


def _rows(comparison: Comparison) -> List[Tuple[str, List[str]]]:
    papers = comparison.papers

    def col(fn: Callable[[ComparedPaper], str]) -> List[str]:
        return [fn(p) for p in papers]

    return [
        ("标题", col(lambda p: p.title or "-")),
        ("arXiv", col(lambda p: p.arxiv_id or "-")),
        ("年份", col(lambda p: str(p.year) if p.year else "-")),
        ("核心贡献", col(lambda p: p.main_contribution or "-")),
        ("新颖之处", col(lambda p: p.novelty or "-")),
        ("关键方法", col(lambda p: "; ".join(p.methods) if p.methods else "-")),
        ("性能/基准", col(lambda p: p.benchmark or "-")),
        ("推荐硬件", col(lambda p: p.hardware or "-")),
        ("官方代码", col(lambda p: p.official_code or "-")),
    ]


def _headers(comparison: Comparison) -> List[str]:
    return [p.arxiv_id or f"#{i + 1}" for i, p in enumerate(comparison.papers)]


def to_markdown(comparison: Comparison) -> str:
    headers = _headers(comparison)
    lines = ["# 论文对比", "", "| 维度 | " + " | ".join(headers) + " |"]
    lines.append("| --- | " + " | ".join("---" for _ in headers) + " |")
    for label, values in _rows(comparison):
        cells = " | ".join(_md_cell(v) for v in values)
        lines.append(f"| {label} | {cells} |")
    if comparison.synthesis:
        lines += ["", "## 对比小结", "", comparison.synthesis]
    lines += ["", "---", "*Generated by [PaperMind](https://github.com/Wenhao-Hua/papermind).*"]
    return "\n".join(lines) + "\n"


def _md_cell(value: str) -> str:
    return value.replace("\n", " ").replace("|", "\\|")


_CSV_FIELDS = ["标题", "arXiv", "年份", "核心贡献", "新颖之处", "关键方法", "性能/基准", "推荐硬件", "官方代码"]


def to_csv(comparison: Comparison) -> str:
    """Return a UTF-8 CSV string with one row per paper (columns = comparison dimensions)."""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=_CSV_FIELDS, lineterminator="\n")
    writer.writeheader()
    for paper in comparison.papers:
        writer.writerow({
            "标题": paper.title or "",
            "arXiv": paper.arxiv_id or "",
            "年份": str(paper.year) if paper.year else "",
            "核心贡献": paper.main_contribution or "",
            "新颖之处": paper.novelty or "",
            "关键方法": "; ".join(paper.methods) if paper.methods else "",
            "性能/基准": paper.benchmark or "",
            "推荐硬件": paper.hardware or "",
            "官方代码": paper.official_code or "",
        })
    return buf.getvalue()


_CSS = (
    "body{font:16px/1.6 -apple-system,Segoe UI,Roboto,'PingFang SC','Microsoft YaHei',sans-serif;"
    "max-width:1000px;margin:40px auto;padding:0 20px;color:#1a1a2e}"
    "table{border-collapse:collapse;width:100%}"
    "th,td{border:1px solid #e5e7eb;padding:8px 12px;text-align:left;vertical-align:top}"
    "th{background:#f3f4f6}td:first-child,th:first-child{font-weight:600;background:#fafafa}"
    "a{color:#5b5bd6}"
)


def to_html(comparison: Comparison) -> str:
    headers = _headers(comparison)
    head = "".join(f"<th>{_e(h)}</th>" for h in headers)
    body = []
    for label, values in _rows(comparison):
        cells = "".join(f"<td>{_html_cell(label, v)}</td>" for v in values)
        body.append(f"<tr><td>{_e(label)}</td>{cells}</tr>")
    synth = f"<h2>对比小结</h2><p>{_e(comparison.synthesis)}</p>" if comparison.synthesis else ""
    return (
        "<!DOCTYPE html><html lang='zh'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>论文对比 · PaperMind</title><style>{_CSS}</style></head><body>"
        "<h1>论文对比</h1>"
        f"<table><thead><tr><th>维度</th>{head}</tr></thead><tbody>{''.join(body)}</tbody></table>"
        f"{synth}"
        "<p style='color:#6b7280;font-size:.85rem'>Generated by "
        "<a href='https://github.com/Wenhao-Hua/papermind'>PaperMind</a>.</p>"
        "</body></html>"
    )


def _html_cell(label: str, value: str) -> str:
    if label == "官方代码" and value.startswith("http"):
        return f"<a href='{_e(value)}'>{_e(value)}</a>"
    return _e(value)


def _e(text) -> str:
    return _html.escape(str(text)) if text is not None else ""
