"""Render a Report to a Markdown document.

Source citations become clickable PDF deep-links (``[Section 3.1](pdf#page=5)``).
Original figures embed as images; AI diagrams render as ```mermaid``` blocks.
Reproduction details use tables/code blocks.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from papermind.output.schema import (
    Connection,
    Reproduction,
    Report,
    Source,
    TechnicalPoint,
)

_DIFFICULTY_BADGE = {"high": "🔴 high", "mid": "🟡 mid", "low": "🟢 low"}


def to_markdown(report: Report, path: Optional[str] = None) -> str:
    md = "\n".join(_render(report))
    if path:
        out = Path(path)
        if out.parent and not out.parent.exists():
            out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
    return md


def _render(report: Report) -> List[str]:
    lines: List[str] = []
    paper = report.paper
    lines.append(f"# {paper.title}")
    lines.append("")
    lines.append(_meta_line(report))
    lines.append("")

    if report.contributions:
        lines += _contributions_md(report)
    if report.technical.details:
        lines += _technical_md(report)
    if report.connections.related_works:
        lines += _connections_md(report.connections.related_works)
    if report.reproduction:
        lines += _reproduction_md(report.reproduction)

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [PaperMind](https://github.com/Wenhao-Hua/papermind).*")
    return lines


def _meta_line(report: Report) -> str:
    paper = report.paper
    bits = []
    if paper.authors:
        shown = ", ".join(paper.authors[:6]) + (" et al." if len(paper.authors) > 6 else "")
        bits.append(f"**Authors:** {shown}")
    if paper.year:
        bits.append(f"**Year:** {paper.year}")
    if paper.arxiv_id:
        bits.append(f"**arXiv:** [{paper.arxiv_id}](https://arxiv.org/abs/{paper.arxiv_id})")
    if paper.pdf_url:
        bits.append(f"[PDF]({paper.pdf_url})")
    return "  •  ".join(bits)


def _source_link(report: Report, section: Optional[str], page: Optional[int]) -> str:
    label = section or (f"p.{page}" if page else "source")
    if page:
        label = f"{section} (p.{page})" if section else f"p.{page}"
    url = report.paper.page_link(page)
    return f"[{label}]({url})" if url else label


def _sources_md(report: Report, sources: List[Source]) -> List[str]:
    if not sources:
        return []
    out = ["", "> **原文出处:**"]
    for s in sources:
        link = _source_link(report, s.section, s.page)
        out.append(f"> - {link}: {s.text}")
    return out


# --------------------------------------------------------------------------- #
def _contributions_md(report: Report) -> List[str]:
    c = report.contributions
    out = ["## 🎯 贡献与创新点", ""]
    out.append(f"**核心贡献:** {c.main_contribution}")
    out.append("")
    out.append(f"**新颖之处:** {c.novelty}")
    out.append("")
    out.append(f"**解决的问题:** {c.problem_solved}")
    out += _sources_md(report, c.sources)
    out.append("")
    return out


def _technical_md(report: Report) -> List[str]:
    out = ["## 🔬 技术细节解释", ""]
    for i, point in enumerate(report.technical.details, start=1):
        out += _technical_point_md(report, i, point)
    return out


def _technical_point_md(report: Report, idx: int, point: TechnicalPoint) -> List[str]:
    badge = _DIFFICULTY_BADGE.get(point.difficulty, point.difficulty)
    out = [f"### {idx}. {point.name}  `{badge}`", ""]
    out.append(point.explanation)
    out.append("")
    if point.analogy:
        out.append(f"> 💡 **类比:** {point.analogy}")
        out.append("")
    if point.source_section or point.page:
        out.append(f"📍 出处: {_source_link(report, point.source_section, point.page)}")
        out.append("")
    if point.figure:
        out += _figure_md(point)
    return out


def _figure_md(point: TechnicalPoint) -> List[str]:
    fig = point.figure
    out: List[str] = []
    if fig.type == "original" and fig.image_path:
        caption = fig.caption or fig.type
        out.append(f"![{caption}]({fig.image_path})")
        out.append(f"*{caption} (论文原图)*")
        out.append("")
    elif fig.type == "ai_generated" and fig.mermaid:
        out.append("```mermaid")
        out.append(fig.mermaid)
        out.append("```")
        out.append(f"*{fig.caption or 'AI 生成示意图'}*")
        out.append("")
    return out


def _connections_md(works: List[Connection]) -> List[str]:
    out = ["## 🔗 知识关联", ""]
    out.append("| 概念 | 相关论文 | 关系 |")
    out.append("| --- | --- | --- |")
    for w in works:
        paper = f"[{w.paper}]({w.arxiv_link})" if w.arxiv_link else w.paper
        out.append(f"| {w.concept} | {paper} | {w.relationship} |")
    out.append("")
    return out


def _reproduction_md(r: Reproduction) -> List[str]:
    out = ["## 🛠️ 复现指南", ""]
    if r.official_code:
        tag = f" (`{r.version_tag}`)" if r.version_tag else ""
        out.append(f"- **官方代码:** [{r.official_code}]({r.official_code}){tag}")
    if r.requirements:
        out.append(f"- **环境要求:** {r.requirements}")
    if r.recommended_hardware:
        out.append(f"- **推荐硬件:** {r.recommended_hardware}")
    if r.key_hyperparams:
        out.append("- **关键超参数:** " + ", ".join(f"`{h}`" for h in r.key_hyperparams))
    out.append("")

    if r.env_setup_steps:
        out.append("### 环境配置步骤")
        out.append("")
        for step in r.env_setup_steps:
            out.append(f"**{step.step}. {step.title}**")
            if step.desc:
                out.append("")
                out.append(step.desc)
            if step.command:
                out.append("")
                out.append("```bash")
                out.append(step.command)
                out.append("```")
            out.append("")

    if r.performance_benchmarks:
        out.append("### 性能基准")
        out.append("")
        out.append("| 设置 | Baseline | 结果 | 加速 | 显存 |")
        out.append("| --- | --- | --- | --- | --- |")
        for b in r.performance_benchmarks:
            out.append(
                f"| {b.setting} | {b.baseline or '-'} | {b.result or '-'} "
                f"| {b.speedup or '-'} | {b.memory or '-'} |"
            )
        out.append("")

    if r.datasets:
        out.append("### 数据集")
        out.append("")
        for d in r.datasets:
            name = f"[{d.name}]({d.link})" if d.link else d.name
            out.append(f"- **{name}** — {d.purpose}")
        out.append("")

    if r.common_errors:
        out.append("### 常见报错与解决")
        out.append("")
        for e in r.common_errors:
            out.append(f"- **报错:** `{e.error}`")
            if e.cause:
                out.append(f"  - 原因: {e.cause}")
            if e.fix_command:
                out.append(f"  - 修复: `{e.fix_command}`")
        out.append("")

    if r.gotchas:
        out.append("### ⚠️ 坑点提示")
        out.append("")
        for g in r.gotchas:
            out.append(f"- {g}")
        out.append("")

    return out
