"""Render a Report to a Markdown document.

Source citations become clickable PDF deep-links (``[Section 3.1](pdf#page=5)``).
Original figures embed as images; AI teaching figures embed as inline SVG data-URIs
by default (legacy Mermaid renders as ```mermaid``` blocks).
Reproduction details use tables/code blocks.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from papermind.output.schema import (
    Connection,
    Reproduction,
    Report,
    Source,
    TechnicalPoint,
)

_DIFFICULTY_BADGE = {"high": "🔴 high", "mid": "🟡 mid", "low": "🟢 low"}


def _mathjax(formula: str) -> str:
    """A multi-line formula uses ``\\\\`` line breaks, which MathJax rejects outside an
    alignment environment ("Misplaced \\"). Wrap such formulas in ``aligned`` so they render."""
    f = (formula or "").strip()
    if "\\\\" in f and "\\begin{" not in f:
        return "\\begin{aligned} " + f + " \\end{aligned}"
    return f


def to_markdown(report: Report, path: Optional[str] = None) -> str:
    md = "\n".join(_render(report))
    if path:
        out = Path(path)
        if out.parent and not out.parent.exists():
            out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
    return md


def _render(report: Report) -> List[str]:
    lines: List[str] = []
    paper = report.paper
    lines.append(f"# {paper.title}")
    lines.append("")
    lines.append(_meta_line(report))
    lines.append("")
    lines += _toc_md(report)

    if report.contributions:
        lines += ['<a id="contributions"></a>', ""]
        lines += _contributions_md(report)
    if report.technical.details:
        lines += ['<a id="technical"></a>', ""]
        lines += _technical_md(report)
    if report.connections.related_works:
        lines += ['<a id="connections"></a>', ""]
        lines += _connections_md(report.connections.related_works)
    if report.reproduction:
        lines += ['<a id="reproduction"></a>', ""]
        lines += _reproduction_md(report.reproduction)

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [PaperMind](https://github.com/Wenhao-Hua/papermind).*")
    return lines


def _toc_md(report: Report) -> List[str]:
    items = []
    if report.contributions:
        items.append(("contributions", "🎯 贡献与创新点"))
    if report.technical.details:
        items.append(("technical", "🔬 技术细节解释"))
    if report.connections.related_works:
        items.append(("connections", "🔗 知识关联"))
    if report.reproduction:
        items.append(("reproduction", "🛠️ 复现指南"))
    if len(items) < 2:
        return []
    return [f"- [{label}](#{anchor})" for anchor, label in items] + [""]


def _meta_line(report: Report) -> str:
    paper = report.paper
    bits = []
    if paper.authors:
        shown = ", ".join(paper.authors[:6]) + (" et al." if len(paper.authors) > 6 else "")
        bits.append(f"**Authors:** {shown}")
    if paper.year:
        bits.append(f"**Year:** {paper.year}")
    if paper.arxiv_id:
        bits.append(f"**arXiv:** [{paper.arxiv_id}](https://arxiv.org/abs/{paper.arxiv_id})")
    if paper.pdf_url:
        bits.append(f"[PDF]({paper.pdf_url})")
    mins = report.reading_minutes()
    bits.append(f"⏱ 约 {mins} 分钟阅读")
    return "  •  ".join(bits)


def _source_link(report: Report, section: Optional[str], page: Optional[int]) -> str:
    label = section or (f"p.{page}" if page else "source")
    if page:
        label = f"{section} (p.{page})" if section else f"p.{page}"
    url = report.paper.page_link(page)
    return f"[{label}]({url})" if url else label


def _sources_md(report: Report, sources: List[Source]) -> List[str]:
    if not sources:
        return []
    out = ["", "> **原文出处:**"]
    for s in sources:
        link = _source_link(report, s.section, s.page)
        mark = "" if s.verified else "⚠️ 未核实 · "
        out.append(f"> - {link}: {mark}{s.text}")
    return out


# --------------------------------------------------------------------------- #
def _contributions_md(report: Report) -> List[str]:
    c = report.contributions
    out = ["## 🎯 贡献与创新点", ""]
    out.append(f"**核心贡献:** {c.main_contribution}")
    out.append("")
    out.append(f"**新颖之处:** {c.novelty}")
    out.append("")
    out.append(f"**解决的问题:** {c.problem_solved}")
    out += _sources_md(report, c.sources)
    out.append("")
    return out


def _technical_md(report: Report) -> List[str]:
    out = ["## 🔬 技术细节解释", ""]
    for i, point in enumerate(report.technical.details, start=1):
        out += _technical_point_md(report, i, point)
    return out


def _technical_point_md(report: Report, idx: int, point: TechnicalPoint) -> List[str]:
    badge = _DIFFICULTY_BADGE.get(point.difficulty, point.difficulty)
    out = [f"### {idx}. {point.name}  `{badge}`", ""]
    out.append(point.explanation)
    out.append("")
    if point.formula:
        out.append(f"$$\n{_mathjax(point.formula)}\n$$")
        out.append("")
    if point.analogy:
        out.append(f"> 💡 **类比:** {point.analogy}")
        out.append("")
    if point.source_section or point.page:
        out.append(f"📍 出处: {_source_link(report, point.source_section, point.page)}")
        out.append("")
    if point.figure:
        out += _figure_md(point)
    return out


def _figure_md(point: TechnicalPoint) -> List[str]:
    fig = point.figure
    out: List[str] = []
    if fig.image_path:  # original figure, or an AI-generated image
        origin = "论文原图" if fig.type == "original" else "AI 生成示意图"
        caption = fig.caption or origin
        out.append(f"![{caption}]({fig.image_path})")
        out.append(f"*{caption} ({origin})*")
        out.append("")
    elif fig.svg:  # self-contained teaching SVG -> embed as a data-URI image
        import base64

        b64 = base64.b64encode(fig.svg.encode("utf-8")).decode("ascii")
        caption = fig.caption or "教学示意图"
        out.append(f"![{caption}](data:image/svg+xml;base64,{b64})")
        out.append(f"*{caption}（教学示意图）*")
        out.append("")
        out += _explain_md(fig.explain)
    elif fig.type == "ai_generated" and fig.mermaid:
        out.append("```mermaid")
        out.append(fig.mermaid)
        out.append("```")
        out.append(f"*{fig.caption or 'AI 生成示意图'}*")
        out.append("")
    return out


def _explain_md(ex) -> List[str]:
    """Render the figure's "how to read it" walkthrough as a blockquote."""
    if not ex or not ex.gist:
        return []
    lines = [f"> **读图**：{ex.gist}"]
    if ex.parts:
        lines.append(">")
        lines += [f"> - {p}" for p in ex.parts]
    if ex.takeaway:
        lines.append(">")
        lines.append(f"> **关键**：{ex.takeaway}")
    lines.append("")
    return lines


def _connections_md(works: List[Connection]) -> List[str]:
    out = ["## 🔗 知识关联", ""]
    out.append("| 概念 | 相关论文 | 关系 |")
    out.append("| --- | --- | --- |")
    for w in works:
        paper = f"[{w.paper}]({w.arxiv_link})" if w.arxiv_link else w.paper
        out.append(f"| {w.concept} | {paper} | {w.relationship} |")
    out.append("")
    return out


def _reproduction_md(r: Reproduction) -> List[str]:
    out = ["## 🛠️ 复现指南", ""]
    if r.code_repo is not None:
        cr = r.code_repo
        badge = " · ✓官方实现" if cr.is_official else ""
        star = f" · ★{cr.stars}" if cr.stars else ""
        tag = f" (`{r.version_tag}`)" if r.version_tag else ""
        out.append(f"- **代码仓库（{cr.source}{badge}{star}）:** [{cr.url}]({cr.url}){tag}")
        cmds = list(cr.install_commands) + list(cr.run_commands)
        if cmds:
            out.append("- **安装 / 运行（取自该仓库，非模型生成）:**")
            out += [f"  - `{c}`" for c in cmds]
    elif r.official_code:
        tag = f" (`{r.version_tag}`)" if r.version_tag else ""
        out.append(f"- **代码仓库:** [{r.official_code}]({r.official_code}){tag}")
    if r.requirements:
        out.append(f"- **环境要求:** {r.requirements}")
    if r.recommended_hardware:
        out.append(f"- **推荐硬件:** {r.recommended_hardware}")
    if r.key_hyperparams:
        out.append("- **关键超参数:** " + ", ".join(f"`{h}`" for h in r.key_hyperparams))
    out.append("")

    if r.env_setup_steps:
        out.append("### 环境配置步骤")
        out.append("")
        for step in r.env_setup_steps:
            out.append(f"**{step.step}. {step.title}**")
            if step.desc:
                out.append("")
                out.append(step.desc)
            if step.command:
                out.append("")
                out.append("```bash")
                out.append(step.command)
                out.append("```")
            out.append("")

    if r.performance_benchmarks:
        out.append("### 性能基准")
        out.append("")
        out.append("| 设置 | Baseline | 结果 | 加速 | 显存 |")
        out.append("| --- | --- | --- | --- | --- |")
        for b in r.performance_benchmarks:
            out.append(
                f"| {b.setting} | {b.baseline or '-'} | {b.result or '-'} "
                f"| {b.speedup or '-'} | {b.memory or '-'} |"
            )
        out.append("")

    if r.datasets:
        out.append("### 数据集")
        out.append("")
        for d in r.datasets:
            name = f"[{d.name}]({d.link})" if d.link else d.name
            out.append(f"- **{name}** — {d.purpose}")
        out.append("")

    if r.common_errors:
        out.append("### 常见报错与解决")
        out.append("")
        for e in r.common_errors:
            out.append(f"- **报错:** `{e.error}`")
            if e.cause:
                out.append(f"  - 原因: {e.cause}")
            if e.fix_command:
                out.append(f"  - 修复: `{e.fix_command}`")
        out.append("")

    if r.gotchas:
        out.append("### ⚠️ 坑点提示")
        out.append("")
        for g in r.gotchas:
            out.append(f"- {g}")
        out.append("")

    return out
