"""Export a report's reproduction guide into runnable artifacts:
a `setup.sh` shell script and a Jupyter notebook.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from papermind.output.schema import Report


def to_setup_script(report: Report) -> str:
    r = report.reproduction
    lines: List[str] = [
        "#!/usr/bin/env bash",
        f"# Reproduction setup for: {report.paper.title}",
    ]
    if report.paper.arxiv_id:
        lines.append(f"# arXiv: https://arxiv.org/abs/{report.paper.arxiv_id}")
    lines += [
        "# Generated by PaperMind — review every command before running.",
        "set -euo pipefail",
        "",
    ]
    if r is None:
        lines.append('echo "No reproduction information available."')
        return "\n".join(lines) + "\n"

    if r.requirements:
        lines.append(f"# Requirements: {r.requirements}")
    if r.recommended_hardware:
        lines.append(f"# Recommended hardware: {r.recommended_hardware}")
    if r.key_hyperparams:
        lines.append(f"# Key hyperparameters: {', '.join(r.key_hyperparams)}")
    lines.append("")

    if r.code_repo is not None:
        cr = r.code_repo
        star = f" · ★{cr.stars}" if cr.stars else ""
        official = " · 官方实现" if cr.is_official else ""
        lines.append(f"# --- 代码仓库（{cr.source}{official}{star}） ---")
        if cr.description:
            lines.append(f"# {cr.description}")
        lines.append(f"git clone {cr.url}")
        repo_dir = cr.url.rstrip("/").rsplit("/", 1)[-1]
        if repo_dir.endswith(".git"):
            repo_dir = repo_dir[:-4]
        lines.append(f"cd {repo_dir}")
        if r.version_tag:
            lines.append(f"git checkout {r.version_tag}")
        for cmd in cr.install_commands:
            lines.append(cmd)
        if cr.run_commands:
            lines.append("")
            lines.append("# 运行命令（取自仓库 README，按需改参数后取消注释）：")
            lines += [f"# {cmd}" for cmd in cr.run_commands]
        lines.append("")
    elif r.official_code:
        lines += ["# --- Official code ---", f"git clone {r.official_code}"]
        if r.version_tag:
            lines.append(f"# cd <repo> && git checkout {r.version_tag}")
        lines.append("")

    for step in r.env_setup_steps:
        lines.append(f"# --- Step {step.step}: {step.title} ---")
        if step.desc:
            lines.append(f"# {step.desc}")
        lines.append(step.command if step.command else "# (no command for this step)")
        lines.append("")

    if r.datasets:
        lines.append("# --- Datasets ---")
        for d in r.datasets:
            lines.append(f"#  - {d.name}: {d.link or '(no link)'}  — {d.purpose}")
        lines.append("")
    if r.common_errors:
        lines.append("# --- Common errors ---")
        for e in r.common_errors:
            lines.append(f"#  ! {e.error}")
            if e.fix_command:
                lines.append(f"#    fix: {e.fix_command}")
        lines.append("")
    if r.gotchas:
        lines.append("# --- Gotchas ---")
        lines += [f"#  - {g}" for g in r.gotchas]

    return "\n".join(lines) + "\n"


def to_notebook(report: Report) -> dict:
    r = report.reproduction
    cells = [_md(_intro(report))]
    if r is not None:
        meta = _meta_block(r)
        if meta:
            cells.append(_md(meta))
        if r.code_repo is not None:
            cr = r.code_repo
            star = f" · ★{cr.stars}" if cr.stars else ""
            official = " · 官方实现" if cr.is_official else ""
            cells.append(_md(f"## 代码仓库（{cr.source}{official}{star}）\n\n<{cr.url}>"))
            repo_dir = cr.url.rstrip("/").rsplit("/", 1)[-1]
            if repo_dir.endswith(".git"):
                repo_dir = repo_dir[:-4]
            clone = [f"!git clone {cr.url}", f"%cd {repo_dir}"] + [f"!{c}" for c in cr.install_commands]
            cells.append(_code("\n".join(clone)))
            if cr.run_commands:
                cells.append(_md("### 运行命令（取自仓库 README，按需改参数）\n"
                                 + "\n".join(f"- `{c}`" for c in cr.run_commands)))
        elif r.official_code:
            cells.append(_code(f"!git clone {r.official_code}"))
        for step in r.env_setup_steps:
            header = f"## {step.step}. {step.title}"
            cells.append(_md(f"{header}\n\n{step.desc}" if step.desc else header))
            if step.command:
                cells.append(_code(f"!{step.command}"))
        trailer = _trailer(r)
        if trailer:
            cells.append(_md(trailer))
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write_setup_script(report: Report, path: str) -> str:
    text = to_setup_script(report)
    _write(path, text)
    return text


def write_notebook(report: Report, path: str) -> dict:
    nb = to_notebook(report)
    _write(path, json.dumps(nb, indent=1, ensure_ascii=False))
    return nb


# --------------------------------------------------------------------------- #
def _intro(report: Report) -> str:
    out = f"# Reproduce: {report.paper.title}\n"
    if report.paper.arxiv_id:
        out += f"\narXiv: https://arxiv.org/abs/{report.paper.arxiv_id}\n"
    out += "\n> Generated by PaperMind — review every command before running."
    return out


def _meta_block(r) -> str:
    bits = []
    if r.requirements:
        bits.append(f"- **Requirements:** {r.requirements}")
    if r.recommended_hardware:
        bits.append(f"- **Recommended hardware:** {r.recommended_hardware}")
    if r.key_hyperparams:
        bits.append("- **Key hyperparameters:** " + ", ".join(f"`{h}`" for h in r.key_hyperparams))
    return "\n".join(bits)


def _trailer(r) -> str:
    parts = []
    if r.datasets:
        parts.append("### Datasets\n" + "\n".join(f"- {d.name}: {d.link or ''} — {d.purpose}" for d in r.datasets))
    if r.common_errors:
        parts.append("### Common errors\n" + "\n".join(f"- `{e.error}` → {e.fix_command or e.cause}" for e in r.common_errors))
    if r.gotchas:
        parts.append("### Gotchas\n" + "\n".join(f"- {g}" for g in r.gotchas))
    return "\n\n".join(parts)


def _md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(text)}


def _code(text: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": _src(text)}


def _src(text: str) -> List[str]:
    lines = text.split("\n")
    return [line + "\n" for line in lines[:-1]] + [lines[-1]]


def _write(path: str, text: str) -> None:
    p = Path(path)
    if p.parent and not p.parent.exists():
        p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
